2024-10-07 21:47:37,792 - ERROR - Invalid HTTP_HOST header: 'adbest.ir'. You may need to add 'adbest.ir' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/abajstor/virtualenv/django_abajstore/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/abajstor/virtualenv/django_abajstore/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/abajstor/virtualenv/django_abajstore/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/abajstor/virtualenv/django_abajstore/3.9/lib/python3.9/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'adbest.ir'. You may need to add 'adbest.ir' to ALLOWED_HOSTS.
2024-10-07 21:47:38,156 - WARNING - Bad Request: /
2024-10-07 21:48:33,725 - ERROR - Invalid HTTP_HOST header: '37.156.145.139'. You may need to add '37.156.145.139' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/abajstor/virtualenv/django_abajstore/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/abajstor/virtualenv/django_abajstore/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/abajstor/virtualenv/django_abajstore/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/abajstor/virtualenv/django_abajstore/3.9/lib/python3.9/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '37.156.145.139'. You may need to add '37.156.145.139' to ALLOWED_HOSTS.
2024-10-07 21:48:33,775 - WARNING - Bad Request: /
2024-10-07 21:48:57,395 - ERROR - Invalid HTTP_HOST header: '37.156.145.139'. You may need to add '37.156.145.139' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/abajstor/virtualenv/django_abajstore/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/abajstor/virtualenv/django_abajstore/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/abajstor/virtualenv/django_abajstore/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/abajstor/virtualenv/django_abajstore/3.9/lib/python3.9/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '37.156.145.139'. You may need to add '37.156.145.139' to ALLOWED_HOSTS.
2024-10-07 21:48:57,413 - WARNING - Bad Request: /
